repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-yaml
            stages: [commit]
            exclude: ^indexed_docs/
          - id: end-of-file-fixer
            stages: [commit]
            types: [python]
            exclude: ^indexed_docs/
          - id: trailing-whitespace
            stages: [commit]
            exclude: ^indexed_docs/

    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
          - id: black
            stages: [commit]
            exclude: ^indexed_docs/

    - repo: https://github.com/charliermarsh/ruff-pre-commit
      # Ruff version.
      rev: "v0.0.243"
      hooks:
          - id: ruff
            args: ["--fix"]
            stages: [commit]
            exclude: ^indexed_docs/

    - repo: https://github.com/PyCQA/bandit
      rev: "1.7.5"
      hooks:
          - id: bandit
            args: ["-x", "tests/*"]
            exclude: ^indexed_docs/
