name: Fetch Node Stats

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  parse_rss:
    runs-on: ubuntu-latest
    env:
      HAS_COMMITS: false
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: stats

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies

      - name: Fetch latest active relay nodes
        run: cd .github/scripts &&
          pip install -r requirements.txt &&
          python3 node_fetcher.py

      - name: Commit files
        id: commit_files
        if: always()
        run: |
          git config --local user.email "millionalgos@pm.me"
          git config --local user.name "github-actions[bot]"

          if [[ -n $(git status --porcelain) ]]; then
            git add -A
            git commit -m "[no-tweet] refreshed node statistics 🤖"
            echo "HAS_COMMITS=true" >> $GITHUB_ENV
          else
            echo "no changes - skipping commit"
            echo "HAS_COMMITS=false" >> $GITHUB_ENV
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: env.HAS_COMMITS != false
        with:
          github_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          branch: stats
